// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TagSeguranca.Api.Infrastructure.Persistence;

#nullable disable

namespace TagSeguranca.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TagDbContext))]
    [Migration("20260613204319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Casa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cep");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("UsuarioAlteracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_alteracao_id");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_criacao_id");

                    b.HasKey("Id")
                        .HasName("pk_casas");

                    b.ToTable("casas", (string)null);
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CasaId")
                        .HasColumnType("uuid")
                        .HasColumnName("casa_id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("date")
                        .HasColumnName("data_evento");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time")
                        .HasColumnName("hora_fim");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Rascunho")
                        .HasColumnName("status");

                    b.Property<Guid>("TipoEventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_evento_id");

                    b.Property<Guid?>("UsuarioAlteracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_alteracao_id");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_criacao_id");

                    b.Property<decimal>("ValorDiaria")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_diaria");

                    b.Property<decimal>("ValorHoraExtra")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_hora_extra");

                    b.HasKey("Id")
                        .HasName("pk_eventos");

                    b.HasIndex("CasaId")
                        .HasDatabaseName("ix_eventos_casa_id");

                    b.HasIndex("TipoEventoId")
                        .HasDatabaseName("ix_eventos_tipo_evento_id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.EventoFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("MotivoRemocao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_remocao");

                    b.Property<bool>("Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pago");

                    b.Property<bool>("Removido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("removido");

                    b.Property<Guid?>("UsuarioAlteracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_alteracao_id");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_criacao_id");

                    b.HasKey("Id")
                        .HasName("pk_evento_funcionarios");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_evento_funcionarios_funcionario_id");

                    b.HasIndex("EventoId", "FuncionarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_evento_funcionarios_evento_id_funcionario_id");

                    b.ToTable("evento_funcionarios", (string)null);
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("chave_pix");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("funcao");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rg");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.Property<Guid?>("UsuarioAlteracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_alteracao_id");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_criacao_id");

                    b.HasKey("Id")
                        .HasName("pk_funcionarios");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_funcionarios_cpf");

                    b.HasIndex("Rg")
                        .IsUnique()
                        .HasDatabaseName("ix_funcionarios_rg");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<int>("QuantidadeEventos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_eventos");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Confirmado")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalHorasExtras")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_horas_extras");

                    b.Property<Guid?>("UsuarioPagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_pagamento_id");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_pagamentos");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_pagamentos_funcionario_id");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.PagamentoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventoFuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_funcionario_id");

                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pagamento_id");

                    b.Property<decimal>("QuantidadeHorasExtras")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantidade_horas_extras");

                    b.Property<decimal>("ValorDiariaPago")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_diaria_pago");

                    b.Property<decimal>("ValorHoraExtraPago")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_hora_extra_pago");

                    b.Property<decimal>("ValorTotalItem")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total_item");

                    b.HasKey("Id")
                        .HasName("pk_pagamento_itens");

                    b.HasIndex("EventoFuncionarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_pagamento_itens_evento_funcionario_id");

                    b.HasIndex("PagamentoId")
                        .HasDatabaseName("ix_pagamento_itens_pagamento_id");

                    b.ToTable("pagamento_itens", (string)null);
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.TipoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("UsuarioAlteracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_alteracao_id");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_criacao_id");

                    b.HasKey("Id")
                        .HasName("pk_tipos_evento");

                    b.ToTable("tipos_evento", (string)null);
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Evento", b =>
                {
                    b.HasOne("TagSeguranca.Api.Domain.Entities.Casa", "Casa")
                        .WithMany("Eventos")
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_casas_casa_id");

                    b.HasOne("TagSeguranca.Api.Domain.Entities.TipoEvento", "TipoEvento")
                        .WithMany("Eventos")
                        .HasForeignKey("TipoEventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_tipos_evento_tipo_evento_id");

                    b.Navigation("Casa");

                    b.Navigation("TipoEvento");
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.EventoFuncionario", b =>
                {
                    b.HasOne("TagSeguranca.Api.Domain.Entities.Evento", "Evento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evento_funcionarios_eventos_evento_id");

                    b.HasOne("TagSeguranca.Api.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany("Eventos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evento_funcionarios_funcionarios_funcionario_id");

                    b.Navigation("Evento");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("TagSeguranca.Api.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany("Pagamentos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_funcionarios_funcionario_id");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.PagamentoItem", b =>
                {
                    b.HasOne("TagSeguranca.Api.Domain.Entities.EventoFuncionario", "EventoFuncionario")
                        .WithOne("PagamentoItem")
                        .HasForeignKey("TagSeguranca.Api.Domain.Entities.PagamentoItem", "EventoFuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamento_itens_evento_funcionarios_evento_funcionario_id");

                    b.HasOne("TagSeguranca.Api.Domain.Entities.Pagamento", "Pagamento")
                        .WithMany("Itens")
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamento_itens_pagamentos_pagamento_id");

                    b.Navigation("EventoFuncionario");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Casa", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Evento", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.EventoFuncionario", b =>
                {
                    b.Navigation("PagamentoItem");
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.Pagamento", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("TagSeguranca.Api.Domain.Entities.TipoEvento", b =>
                {
                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
